// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDITy9BCiVeB7kxRwomPtKIDelwpdBux7A',
    appId: '1:664368582662:android:e67e798544c552887cf387',
    messagingSenderId: '664368582662',
    projectId: 'coop-d1eaf',
    databaseURL: 'https://coop-d1eaf.firebaseio.com',
    storageBucket: 'coop-d1eaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApyt76ReGszMMdHxjtiouktyKf5U5ZwuA',
    appId: '1:664368582662:ios:93c6bd4d19e77d067cf387',
    messagingSenderId: '664368582662',
    projectId: 'coop-d1eaf',
    databaseURL: 'https://coop-d1eaf.firebaseio.com',
    storageBucket: 'coop-d1eaf.appspot.com',
    androidClientId: '664368582662-1kqmtkt0eghp9mevkchl520fk5i1c78u.apps.googleusercontent.com',
    iosClientId: '664368582662-a9bsjbk8f84orohoa5ubqd23eeecisvn.apps.googleusercontent.com',
    iosBundleId: 'com.technikh.rnginfra.residents',
  );
}
