// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.json';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzgEwAUTjQhOPPqb1G8VuXlXCuOZhKjgU',
    appId: '1:664368582662:web:5e4e64f68c9a89517cf387',
    messagingSenderId: '664368582662',
    projectId: 'coop-d1eaf',
    authDomain: 'coop-d1eaf.firebaseapp.com',
    databaseURL: 'https://coop-d1eaf.firebaseio.com',
    storageBucket: 'coop-d1eaf.appspot.com',
    measurementId: 'G-70WG54S0QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDITy9BCiVeB7kxRwomPtKIDelwpdBux7A',
    appId: '1:664368582662:android:d3e7476dbbd882f37cf387',
    messagingSenderId: '664368582662',
    projectId: 'coop-d1eaf',
    databaseURL: 'https://coop-d1eaf.firebaseio.com',
    storageBucket: 'coop-d1eaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApyt76ReGszMMdHxjtiouktyKf5U5ZwuA',
    appId: '1:664368582662:ios:f0557eeb2e723bcb7cf387',
    messagingSenderId: '664368582662',
    projectId: 'coop-d1eaf',
    databaseURL: 'https://coop-d1eaf.firebaseio.com',
    storageBucket: 'coop-d1eaf.appspot.com',
    androidClientId: '664368582662-1kqmtkt0eghp9mevkchl520fk5i1c78u.apps.googleusercontent.com',
    iosClientId: '664368582662-s1rdcakcnbtbrgjpapj3um8m0smkup28.apps.googleusercontent.com',
    iosBundleId: 'com.technikh.rnginfra.visitors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApyt76ReGszMMdHxjtiouktyKf5U5ZwuA',
    appId: '1:664368582662:ios:71cd3a693503a8857cf387',
    messagingSenderId: '664368582662',
    projectId: 'coop-d1eaf',
    databaseURL: 'https://coop-d1eaf.firebaseio.com',
    storageBucket: 'coop-d1eaf.appspot.com',
    androidClientId: '664368582662-1kqmtkt0eghp9mevkchl520fk5i1c78u.apps.googleusercontent.com',
    iosClientId: '664368582662-ej5flv84939qs1kvlufpj3ogro9d940d.apps.googleusercontent.com',
    iosBundleId: 'com.technikh.rnginfra.guards',
  );
}
